### ISSUE TITLE
How to retract without position (need home first) error

### ISSUE THREAD

**Issue by ZhenyaKa** [KevinOConnor/klipper#1178]
I have this command in Octoprint:

```
controls:
- children:
  - commands:
    - G91 E
    - G1 E%(rtr)s F1200
    - G1 E%(rtr)s F1200
    - G1 E%(rtr)s F1200
    - G1 E%(rtr)s F1200
    - G90
    - M84
    input:
    - default: -140
      name: Retract dst
      parameter: rtr
    name: Fast retract ___x4___
    type: parametric_commands
  - commands:
    - G91
    - G1 E%(extr)s F1200
    - G1 E%(extr)s F1200
    - G1 E%(extr)s F1200
    - G1 E%(extr)s F1200
    - G90
    - M84
    input:
    - default: 125
      name: Extrude dst
      parameter: extr
    name: Fast extrude x4
    type: parametric_commands
  name: Filament
  type: section
```

For replace filament. 

But when I run retract I receive "Must home axis first error". It don't move the table, but extruder only.
How to solve this problem?

I have button for fake XYZ coords and press it each time before replacing filament but I think this is not good solution.
