### ISSUE TITLE
Pause -->  disconneceted Octoprint but print doesen't stop..

### ISSUE THREAD

**Issue by Hywelmartin** [KevinOConnor/klipper#1467]
So I printed(v-SD) and saw a booger on my hotend. So to wipe it of I used my Pause_park macro..
It took a while to get executed so I triggered it again before. so I got multiple pauses.. And the print head didn't Park like it should..(I have to test this more)
After a while i noticed that Octoprint got disconnected and the print went on happily, so I tried to reconnect but that didn't work... for some time... then it connected and the print stopped.. sort of..
The print head just stopped and heaters was still on at set temperatures, motor was engaged. Fire hazard?? the Idle timer would probably turn everything off..

I believe that this is mostly a octoprint issue. Will  it  be fixed by the upcoming release that adress "unknownCommandsNeedAck: true"? 
I have edited the config.yaml
```
serial:
  abortHeatupOnCancel: false
  additionalPorts:
  - /tmp/printer
  autoconnect: true
  baudrate: 250000
  disconnectOnErrors: false
  port: /tmp/printer
  timeout:
    temperature: 9.0
    temperatureAutoreport: 3.0
    temperatureTargetSet: 6.0
    unknownCommandsNeedAck: true
```

[klippy.log.zip](https://github.com/KevinOConnor/klipper/files/3025304/klippy.log.zip)
